# Generated by Django 4.1 on 2024-07-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
