# Generated by Django 4.1 on 2024-07-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0002_dress_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('dress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dresses.dress')),
            ],
        ),
    ]
