# Generated by Django 4.1 on 2024-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0003_remove_dress_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='first_pic',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
